### ISSUE TITLE
Directory Issue with the "kernel/" folder.

### ISSUE THREAD

**Issue by aristonlorenzo** [Null-LLC/Hydra#2]
For some reason, on commit `3b67285ad60769b8db7c34bf5714a0d6bc996ea5` which is the "*Stuff, so many stuff*" commit by @FiReLScar, the kernel directory on GitHub split into `Kernel/` and `kernel/`. Oddly, when cloning the repository, the folder's are combined as one. If anyone would like to take a stab and figure it out, that would be greatly appreciated.

**Comment by aristonlorenzo** [comment]
Fixed on Ubuntu

**Comment by FiReLScar** [comment]
Tf
